services:
  nats:
    image: nats:alpine
    ports:
      - 4224:4224
      - 4222:4222
    volumes:
      - ./nats/nats-2.conf:/app/nats.conf

    command: -c /app/nats.conf

  # chroma_db:
  #   image: chromadb/chroma
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./client/chroma_data:/data
  
  # ui:
  #   image: oven/bun
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./ui:/app
  #   working_dir: /app
  #   command: dev

  # mcp-client:
  #   image: oven/bun
  #   volumes:
  #     - ./client:/app/client
  #     - ./server:/app/server
  #   command: bun --watch --hot /app/client/src/index.ts

  # transcription_service:
  #   build: services/tts
  #   volumes:
  #     - ./services/tts:/app
  #     - transcription_service_cache:/root/.cache
  #   # deploy:
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #       - driver: nvidia
  #   #         capabilities: [gpu]
  #   #         count: all
  #   command: python3 /app/client.py

  # ollama:
  #   build: ./ollama
  #   ports:
  #     - 11434:11434
  #   # deploy:
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #       - driver: nvidia
  #   #         capabilities: [gpu]
  #   #         count: all
  #   volumes:
  #     - ollama_data:/root/.ollama

volumes:
  ollama_data:
  transcription_service_cache: